version: 2
sources:
  - name: qwt_raw
    database: "{{env_var('DBT_SOURCEDB','QWT_ANALYTICS')}}"
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: ordersdetails
      - name: employees
      - name: offices
      - name: shipments
      - name: suppliers
